package com.kotlin.illusiontoreality.currencyconverter.controller

import com.kotlin.illusiontoreality.currencyconverter.pojo.ConvertResponse


/*
 This class is central hub to save currencies, convert currencies, save default and save network response currencies.
 */
object CurrencyConverterController {

    var currencyMapWithUSD: HashMap<String, Double>? = null

    init {
        currencyMapWithUSD = HashMap<String, Double>()
    }

    fun add(key: String, value: Double) {
        currencyMapWithUSD?.put(key, value)
    }

    fun clear() {
        currencyMapWithUSD?.clear()
    }

    fun get(key: String?): Double? {
        if (currencyMapWithUSD?.containsKey(key)!!) {
            return currencyMapWithUSD?.get(key)
        }
        return 0.0
    }

    fun remove(key: String) {
        if (currencyMapWithUSD != null && currencyMapWithUSD!!.containsKey(key)) {
            currencyMapWithUSD!!.remove(key)
        }
    }

    fun getMap(): HashMap<String, Double>? {
        return currencyMapWithUSD
    }

    fun convertFromTo(from: String?, to: String?, value: Double): Double? {
        if (from.equals("USD")) {
            return get(to)?.times(value)
        } else if (to.equals("USD")) {
            val fromValue = get(from)
            if (fromValue != 0.0) {
                return (1 / fromValue!!) * value
            }
            return 0.0
        } else {
            val fromValue = get(from)
            val toValue = get(to)
            return (1 / fromValue!!) * toValue!! * value
        }
        return 0.0

    }

    fun addDefaultCurrencies() {
        clear()

        add("AED", 3.672982)
        add("AFN", 77.050095)
        add("ALL", 102.449831)
        add("AMD", 509.139925)
        add("ANG", 1.795836)
        add("AOA", 654.817021)
        add("ARS", 81.482339)
        add("AUD", 1.353455)
        add("AWG", 1.8)
        add("AZN", 1.690866)
        add("BAM", 1.623486)
        add("BBD", 2.020106)
        add("BDT", 84.83476)
        add("BGN", 1.619083)
        add("BHD", 0.377054)
        add("BIF", 1944.0)
        add("BMD", 1.0)
        add("BND", 1.340766)
        add("BOB", 6.898192)
        add("BRL", 5.227401)
        add("BSD", 0.999959)
        add("BTC", 5.2788572e-5)
        add("BTN", 73.817916)
        add("BWP", 11.085856)
        add("BYN", 2.593573)
        add("BYR", 19600.0)
        add("BZD", 2.016669)
        add("CAD", 1.293495)
        add("CDF", 1971.000372)
        add("CHF", 0.895655)
        add("CLF", 0.027384)
        add("CLP", 755.801793)
        add("CNY", 6.563301)
        add("COP", 3525.66)
        add("CRC", 604.120836)
        add("CUC", 1.0)
        add("CUP", 26.5)
        add("CVE", 91.598411)
        add("CZK", 21.823702)
        add("DJF", 178.100045)
        add("DKK", 6.15545)
        add("DOP", 58.250155)
        add("DZD", 129.231075)
        add("EGP", 15.658895)
        add("ERN", 15.000368)
        add("ETB", 37.999849)
        add("EUR", 0.826835)
        add("FJD", 2.059398)
        add("FKP", 0.748993)
        add("GBP", 0.748865)
        add("GEL", 3.32501)
        add("GGP", 0.748993)
        add("GHS", 5.859826)
        add("GIP", 0.748993)
        add("GMD", 51.749974)
        add("GNF", 9825.000108)
        add("GTQ", 7.818565)
        add("GYD", 209.709286)
        add("HKD", 7.75158)
        add("HNL", 24.297226)
        add("HRK", 6.242897)
        add("HTG", 67.463598)
        add("HUF", 297.225987)
        add("IDR", 14184.7)
        add("ILS", 3.28945)
        add("IMP", 0.748993)
        add("INR", 73.7322)
        add("IQD", 1190.5)
        add("IRR", 42104.999914)
        add("ISK", 128.610298)
        add("JEP", 0.748993)
        add("JMD", 146.050523)
        add("JOD", 0.709018)
        add("JPY", 104.522962)
        add("KES", 110.597688)
        add("KGS", 84.799196)
        add("KHR", 4050.000358)
        add("KMF", 412.250251)
        add("KPW", 900.056154)
        add("KRW", 1102.269424)
        add("KWD", 0.304602)
        add("KYD", 0.833728)
        add("KZT", 425.106457)
        add("LAK", 9277.496685)
        add("LBP", 1516.999953)
        add("LKR", 185.837159)
        add("LRD", 158.000321)
        add("LSL", 15.339727)
        add("LTL", 2.95274)
        add("LVL", 0.60489)
        add("LYD", 1.34988)
        add("MAD", 9.0375)
        add("MDL", 17.257257)
        add("MGA", 3784.999767)
        add("MKD", 51.195318)
        add("MMK", 1323.620591)
        add("MNT", 2845.410109)
        add("MOP", 7.987896)
        add("MRO", 357.000515)
        add("MUR", 39.797868)
        add("MVR", 15.400376)
        add("MWK", 770.000031)
        add("MXN", 20.028903)
        add("MYR", 4.077499)
        add("MZN", 74.260018)
        add("NAD", 15.340538)
        add("NGN", 380.999794)
        add("NIO", 34.849972)
        add("NOK", 8.817904)
        add("NPR", 118.108765)
        add("NZD", 1.41715)
        add("OMR", 0.384992)
        add("PAB", 1.00049)
        add("PEN", 3.604998)
        add("PGK", 3.5225)
        add("PHP", 48.040496)
        add("PKR", 160.37502)
        add("PLN", 3.71145)
        add("PYG", 7042.884893)
        add("QAR", 3.641022)
        add("RON", 4.028602)
        add("RSD", 97.215035)
        add("RUB", 75.11365)
        add("RWF", 987.5)
        add("SAR", 3.751014)
        add("SBD", 8.066615)
        add("SCR", 21.206409)
        add("SDG", 55.295212)
        add("SEK", 8.49686)
        add("SGD", 1.338765)
        add("SHP", 0.748993)
        add("SLL", 10015.000499)
        add("SOS", 580.99973)
        add("SRD", 14.154002)
        add("STD", 21031.906016)
        add("SVC", 8.754701)
        add("SYP", 512.935906)
        add("SZL", 15.339904)
        add("THB", 30.210271)
        add("TJS", 11.332797)
        add("TMT", 3.5)
        add("TND", 2.715004)
        add("TOP", 2.286297)
        add("TRY", 7.864395)
        add("TTD", 6.798413)
        add("TWD", 28.496503)
        add("TZS", 2319.000114)
        add("UAH", 28.436916)
        add("UGX", 3697.557817)
        add("USD", 1.0)
        add("UYU", 42.554499)
        add("UZS", 10430.000055)
        add("VEF", 9.987501)
        add("VND", 23130.0)
        add("VUV", 111.026497)
        add("WST", 2.551707)
        add("XAF", 544.538896)
        add("XAG", 0.041682)
        add("XAU", 0.000547)
        add("XCD", 2.70255)
        add("XDR", 0.700144)
        add("XOF", 548.000289)
        add("XPF", 99.225026)
        add("YER", 250.30203)
        add("ZAR", 15.31795)
        add("ZMK", 9001.202118)
        add("ZMW", 21.035207)
        add("ZWL", 321.999941)

    }

    fun addAllTenCurrencies(convertResponse: ConvertResponse) {
        clear()

        add("AED", convertResponse.quotes?.uSDAED!!)
        add("AFN", convertResponse.quotes?.uSDAFN!!)
        add("ALL", convertResponse.quotes?.uSDALL!!)
        add("AMD", convertResponse.quotes?.uSDAMD!!)
        add("ANG", convertResponse.quotes?.uSDANG!!)
        add("AOA", convertResponse.quotes?.uSDAOA!!)
        add("ARS", convertResponse.quotes?.uSDARS!!)
        add("AUD", convertResponse.quotes?.uSDAUD!!)
        add("AWG", convertResponse.quotes?.uSDAWG!!)
        add("AZN", convertResponse.quotes?.uSDAZN!!)
        add("BAM", convertResponse.quotes?.uSDBAM!!)
        add("BBD", convertResponse.quotes?.uSDBBD!!)
        add("BDT", convertResponse.quotes?.uSDBDT!!)
        add("BGN", convertResponse.quotes?.uSDBGN!!)
        add("BHD", convertResponse.quotes?.uSDBHD!!)
        add("BIF", convertResponse.quotes?.uSDBIF!!)
        add("BMD", convertResponse.quotes?.uSDBMD!!)
        add("BND", convertResponse.quotes?.uSDBND!!)
        add("BOB", convertResponse.quotes?.uSDBOB!!)
        add("BRL", convertResponse.quotes?.uSDBRL!!)
        add("BSD", convertResponse.quotes?.uSDBSD!!)
        add("BTC", convertResponse.quotes?.uSDBTC!!)
        add("BTN", convertResponse.quotes?.uSDBTN!!)
        add("BWP", convertResponse.quotes?.uSDBWP!!)
        add("BYN", convertResponse.quotes?.uSDBYN!!)
        add("BYR", convertResponse.quotes?.uSDBYR!!)
        add("BZD", convertResponse.quotes?.uSDBZD!!)
        add("CAD", convertResponse.quotes?.uSDCAD!!)
        add("CDF", convertResponse.quotes?.uSDCDF!!)
        add("CHF", convertResponse.quotes?.uSDCHF!!)
        add("CLF", convertResponse.quotes?.uSDCLF!!)
        add("CLP", convertResponse.quotes?.uSDCLP!!)
        add("CNY", convertResponse.quotes?.uSDCNY!!)
        add("COP", convertResponse.quotes?.uSDCOP!!)
        add("CRC", convertResponse.quotes?.uSDCRC!!)
        add("CUC", convertResponse.quotes?.uSDCUC!!)
        add("CUP", convertResponse.quotes?.uSDCUP!!)
        add("CVE", convertResponse.quotes?.uSDCVE!!)
        add("CZK", convertResponse.quotes?.uSDCZK!!)
        add("DJF", convertResponse.quotes?.uSDDJF!!)
        add("DKK", convertResponse.quotes?.uSDDKK!!)
        add("DOP", convertResponse.quotes?.uSDDOP!!)
        add("DZD", convertResponse.quotes?.uSDDZD!!)
        add("EGP", convertResponse.quotes?.uSDEGP!!)
        add("ERN", convertResponse.quotes?.uSDERN!!)
        add("ETB", convertResponse.quotes?.uSDETB!!)
        add("EUR", convertResponse.quotes?.uSDEUR!!)
        add("FJD", convertResponse.quotes?.uSDFJD!!)
        add("FKP", convertResponse.quotes?.uSDFKP!!)
        add("GBP", convertResponse.quotes?.uSDGBP!!)
        add("GEL", convertResponse.quotes?.uSDGEL!!)
        add("GGP", convertResponse.quotes?.uSDGGP!!)
        add("GHS", convertResponse.quotes?.uSDGHS!!)
        add("GIP", convertResponse.quotes?.uSDGIP!!)
        add("GMD", convertResponse.quotes?.uSDGMD!!)
        add("GNF", convertResponse.quotes?.uSDGNF!!)
        add("GTQ", convertResponse.quotes?.uSDGTQ!!)
        add("GYD", convertResponse.quotes?.uSDGYD!!)
        add("HKD", convertResponse.quotes?.uSDHKD!!)
        add("HNL", convertResponse.quotes?.uSDHNL!!)
        add("HRK", convertResponse.quotes?.uSDHRK!!)
        add("HTG", convertResponse.quotes?.uSDHTG!!)
        add("HUF", convertResponse.quotes?.uSDHUF!!)
        add("IDR", convertResponse.quotes?.uSDIDR!!)
        add("ILS", convertResponse.quotes?.uSDILS!!)
        add("IMP", convertResponse.quotes?.uSDIMP!!)
        add("INR", convertResponse.quotes?.uSDINR!!)
        add("IQD", convertResponse.quotes?.uSDIQD!!)
        add("IRR", convertResponse.quotes?.uSDIRR!!)
        add("ISK", convertResponse.quotes?.uSDISK!!)
        add("JEP", convertResponse.quotes?.uSDJEP!!)
        add("JMD", convertResponse.quotes?.uSDJMD!!)
        add("JOD", convertResponse.quotes?.uSDJOD!!)
        add("JPY", convertResponse.quotes?.uSDJPY!!)
        add("KES", convertResponse.quotes?.uSDKES!!)
        add("KGS", convertResponse.quotes?.uSDKGS!!)
        add("KHR", convertResponse.quotes?.uSDKHR!!)
        add("KMF", convertResponse.quotes?.uSDKMF!!)
        add("KPW", convertResponse.quotes?.uSDKPW!!)
        add("KRW", convertResponse.quotes?.uSDKRW!!)
        add("KWD", convertResponse.quotes?.uSDKWD!!)
        add("KYD", convertResponse.quotes?.uSDKYD!!)
        add("KZT", convertResponse.quotes?.uSDKZT!!)
        add("LAK", convertResponse.quotes?.uSDLAK!!)
        add("LBP", convertResponse.quotes?.uSDLBP!!)
        add("LKR", convertResponse.quotes?.uSDLKR!!)
        add("LRD", convertResponse.quotes?.uSDLRD!!)
        add("LSL", convertResponse.quotes?.uSDLSL!!)
        add("LTL", convertResponse.quotes?.uSDLTL!!)
        add("LVL", convertResponse.quotes?.uSDLVL!!)
        add("LYD", convertResponse.quotes?.uSDLYD!!)
        add("MAD", convertResponse.quotes?.uSDMAD!!)
        add("MDL", convertResponse.quotes?.uSDMDL!!)
        add("MGA", convertResponse.quotes?.uSDMGA!!)
        add("MKD", convertResponse.quotes?.uSDMKD!!)
        add("MMK", convertResponse.quotes?.uSDMMK!!)
        add("MNT", convertResponse.quotes?.uSDMNT!!)
        add("MOP", convertResponse.quotes?.uSDMOP!!)
        add("MRO", convertResponse.quotes?.uSDMRO!!)
        add("MUR", convertResponse.quotes?.uSDMUR!!)
        add("MVR", convertResponse.quotes?.uSDMVR!!)
        add("MWK", convertResponse.quotes?.uSDMWK!!)
        add("MXN", convertResponse.quotes?.uSDMXN!!)
        add("MYR", convertResponse.quotes?.uSDMYR!!)
        add("MZN", convertResponse.quotes?.uSDMZN!!)
        add("NAD", convertResponse.quotes?.uSDNAD!!)
        add("NGN", convertResponse.quotes?.uSDNGN!!)
        add("NIO", convertResponse.quotes?.uSDNIO!!)
        add("NOK", convertResponse.quotes?.uSDNOK!!)
        add("NPR", convertResponse.quotes?.uSDNPR!!)
        add("NZD", convertResponse.quotes?.uSDNZD!!)
        add("OMR", convertResponse.quotes?.uSDOMR!!)
        add("PAB", convertResponse.quotes?.uSDPAB!!)
        add("PEN", convertResponse.quotes?.uSDPEN!!)
        add("PGK", convertResponse.quotes?.uSDPGK!!)
        add("PHP", convertResponse.quotes?.uSDPHP!!)
        add("PKR", convertResponse.quotes?.uSDPKR!!)
        add("PLN", convertResponse.quotes?.uSDPLN!!)
        add("PYG", convertResponse.quotes?.uSDPYG!!)
        add("QAR", convertResponse.quotes?.uSDQAR!!)
        add("RON", convertResponse.quotes?.uSDRON!!)
        add("RSD", convertResponse.quotes?.uSDRSD!!)
        add("RUB", convertResponse.quotes?.uSDRUB!!)
        add("RWF", convertResponse.quotes?.uSDRWF!!)
        add("SAR", convertResponse.quotes?.uSDSAR!!)
        add("SBD", convertResponse.quotes?.uSDSBD!!)
        add("SCR", convertResponse.quotes?.uSDSCR!!)
        add("SDG", convertResponse.quotes?.uSDSDG!!)
        add("SEK", convertResponse.quotes?.uSDSEK!!)
        add("SGD", convertResponse.quotes?.uSDSGD!!)
        add("SHP", convertResponse.quotes?.uSDSHP!!)
        add("SLL", convertResponse.quotes?.uSDSLL!!)
        add("SOS", convertResponse.quotes?.uSDSOS!!)
        add("SRD", convertResponse.quotes?.uSDSRD!!)
        add("STD", convertResponse.quotes?.uSDSTD!!)
        add("SVC", convertResponse.quotes?.uSDSVC!!)
        add("SYP", convertResponse.quotes?.uSDSYP!!)
        add("SZL", convertResponse.quotes?.uSDSZL!!)
        add("THB", convertResponse.quotes?.uSDTHB!!)
        add("TJS", convertResponse.quotes?.uSDTJS!!)
        add("TMT", convertResponse.quotes?.uSDTMT!!)
        add("TND", convertResponse.quotes?.uSDTND!!)
        add("TOP", convertResponse.quotes?.uSDTOP!!)
        add("TRY", convertResponse.quotes?.uSDTRY!!)
        add("TTD", convertResponse.quotes?.uSDTTD!!)
        add("TWD", convertResponse.quotes?.uSDTWD!!)
        add("TZS", convertResponse.quotes?.uSDTZS!!)
        add("UAH", convertResponse.quotes?.uSDUAH!!)
        add("UGX", convertResponse.quotes?.uSDUGX!!)
        add("USD", convertResponse.quotes?.uSDUSD!!)
        add("UYU", convertResponse.quotes?.uSDUYU!!)
        add("UZS", convertResponse.quotes?.uSDUZS!!)
        add("VEF", convertResponse.quotes?.uSDVEF!!)
        add("VND", convertResponse.quotes?.uSDVND!!)
        add("VUV", convertResponse.quotes?.uSDVUV!!)
        add("WST", convertResponse.quotes?.uSDWST!!)
        add("XAF", convertResponse.quotes?.uSDXAF!!)
        add("XAG", convertResponse.quotes?.uSDXAG!!)
        add("XAU", convertResponse.quotes?.uSDXAU!!)
        add("XCD", convertResponse.quotes?.uSDXCD!!)
        add("XDR", convertResponse.quotes?.uSDXDR!!)
        add("XOF", convertResponse.quotes?.uSDXOF!!)
        add("XPF", convertResponse.quotes?.uSDXPF!!)
        add("YER", convertResponse.quotes?.uSDYER!!)
        add("ZAR", convertResponse.quotes?.uSDZAR!!)
        add("ZMK", convertResponse.quotes?.uSDZMK!!)
        add("ZMW", convertResponse.quotes?.uSDZMW!!)
        add("ZWL", convertResponse.quotes?.uSDZWL!!)
    }
}